name: CI
on:
  push:
    branches:
      - "*"
      # - "gh-pages"
  pull_request:
    branches:
      - "gh-pages"
jobs:
  linting:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        pip install -U setuptools "tox>=3.23.0,<4"
    - run: tox -e format-check,lint,typecheck
